version: "3.9"

services:
  app:
    build: ./infra/php
    restart: always
    volumes:
      - sync:/work

  web:
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    restart: always
    volumes:
      - db_store:/var/lib/mysql
    environment:
      ### 任意に変更 ################################
      MYSQL_DATABASE: todo #データベース名
      MYSQL_USER: user #ユーザー名
      MYSQL_PASSWORD: password #パスワード
      MYSQL_ROOT_PASSWORD: password #ルートパスワード
      #############################################
      TZ: 'Asia/Tokyo'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      ### 任意に変更 ################################
      PMA_USER: user #MYSQL_USERと同値
      PMA_PASSWORD: password #MYSQL_PASSWORDと同値
      #############################################

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db_store:
  sync:
    external: true